import type { Skill } from "@/features/skills/schema";
import { createStore } from "./store";

// The BFF's skills data source — an in-memory seed (verbatim from the design mockup) behind
// the shared CRUD store. When the skills registry comes online this becomes a downstream
// client and the router above is unchanged.
function seedSkills(): Skill[] {
  return [
    {
      id: "test-runner",
      name: "Test Runner",
      slug: "test-runner",
      category: "testing",
      description: "Run the suite, summarize failures",
      summary:
        "Detects the test command from the repo — pytest, jest, or go test — and summarizes failures.",
      version: "v1.4",
      status: "active",
      author: "Jules",
      tools: ["Bash", "Read"],
      steps: [
        "Read the repo manifest to pick the runner.",
        "Run only the tests touching changed files first.",
        "On failure, return the shortest reproducing command.",
        "Summarize each failure with a likely root cause.",
      ],
      usedBy: 4,
      invocations: "1,204",
      updated: "3 days ago",
      versionHistory: [
        { version: "v1.4", when: "3 days ago", note: "Detect go test runners" },
        { version: "v1.3", when: "3 weeks ago", note: "Group failures by root cause" },
        { version: "v1.0", when: "2 months ago", note: "Initial release" },
      ],
    },
    {
      id: "pr-desc",
      name: "PR Description",
      slug: "pr-description",
      category: "git",
      description: "Write a structured PR body from a diff",
      summary: "Turns a diff into a reviewer-friendly PR body grouped by intent.",
      version: "v3.0",
      status: "used",
      author: "Jules",
      tools: [],
      steps: [
        "Group the diff by intent, not by file.",
        "Lead with the why, then the what.",
        "Call out risk, migrations and rollout notes.",
      ],
      usedBy: 5,
      invocations: "2,940",
      updated: "1 week ago",
      versionHistory: [
        { version: "v3.0", when: "1 week ago", note: "Group by intent, not file" },
        { version: "v2.0", when: "1 month ago", note: "Add risk callouts" },
        { version: "v1.0", when: "4 months ago", note: "Initial release" },
      ],
    },
    {
      id: "conv-commits",
      name: "Conventional Commits",
      slug: "conventional-commits",
      category: "git",
      description: "Format commit messages to spec",
      summary: "Formats messages to the Conventional Commits spec.",
      version: "v2.1",
      status: "used",
      author: "meridian",
      tools: [],
      steps: [
        "Pick the type from the change (feat, fix, chore…).",
        "Scope by package.",
        "Keep the subject under 72 characters.",
      ],
      usedBy: 8,
      invocations: "6,110",
      updated: "2 weeks ago",
      versionHistory: [
        { version: "v2.1", when: "2 weeks ago", note: "Scope by package" },
        { version: "v2.0", when: "2 months ago", note: "Full spec compliance" },
        { version: "v1.0", when: "5 months ago", note: "Initial release" },
      ],
    },
    {
      id: "changelog",
      name: "Changelog",
      slug: "changelog",
      category: "git",
      description: "Append a Keep-a-Changelog entry",
      summary: "Appends a Keep-a-Changelog entry under Unreleased.",
      version: "v1.2",
      status: "draft",
      author: "Jules",
      tools: ["Read", "Write"],
      steps: [
        "Classify the change (Added / Changed / Fixed).",
        "Write a human-facing line, not a commit message.",
      ],
      usedBy: 0,
      invocations: "—",
      updated: "yesterday",
      versionHistory: [{ version: "v1.2", when: "yesterday", note: "Draft — Unreleased section" }],
    },
    {
      id: "repo-map",
      name: "Repo Map",
      slug: "repo-map",
      category: "analysis",
      description: "Build a structural map of a codebase",
      summary: "Builds a structural map: entrypoints, models and cross-module usages.",
      version: "v1.0",
      status: "used",
      author: "meridian",
      tools: ["Bash", "Read"],
      steps: [
        "Walk the package tree, skipping vendored dirs.",
        "Extract entrypoints and public exports.",
        "Emit a dependency map the builders can load.",
      ],
      usedBy: 3,
      invocations: "880",
      updated: "1 month ago",
      versionHistory: [{ version: "v1.0", when: "1 month ago", note: "Initial release" }],
    },
    {
      id: "sql-migration",
      name: "SQL Migration",
      slug: "sql-migration",
      category: "data",
      description: "Generate reversible migrations",
      summary: "Generates reversible, idempotent SQL migrations.",
      version: "v2.0",
      status: "used",
      author: "meridian",
      tools: ["Read", "Write"],
      steps: [
        "Diff the target schema against head.",
        "Emit paired up + down migrations.",
        "Guard with IF NOT EXISTS where safe.",
      ],
      usedBy: 2,
      invocations: "1,510",
      updated: "5 days ago",
      versionHistory: [
        { version: "v2.0", when: "5 days ago", note: "Reversible up/down pairs" },
        { version: "v1.0", when: "3 months ago", note: "Initial release" },
      ],
    },
  ];
}

export const skillsStore = createStore(seedSkills);
